kind: pipeline
name: build:tensorflow

platform:
  os: linux
  arch: arm

clone:
  depth: 1

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: build:tensorflow
  image: plugins/docker:linux-arm
  group: build
  settings:
    repo: alxda/secam
    dry_run: true
    dockerfile: ./rpi-tensorflow/Dockerfile
- name: publish:tensorflow
  image: plugins/docker:linux-arm
  # secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD, DOCKER_EMAIL ]
  username: ${DOCKER_USERNAME}
  password: ${DOCKER_PASSWORD}
  email: ${DOCKER_EMAIL}
  repo: alxda/secam
  tags:
    - latest
  dockerfile: ./rpi-tensorflow/Dockerfile
  context: ./rpi-tensorflow/

---
kind: pipeline
name: build:node-red

platform:
  os: linux
  arch: arm

clone:
  depth: 1

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: build:node-red
  image: plugins/docker:linux-arm
  group: build
  settings:
    repo: alxda/secam
    dry_run: true
    dockerfile: ./rpi-node-red/Dockerfile