kind: pipeline
name: build:tensorflow

platform:
  os: linux
  arch: arm

clone:
  depth: 1

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
# Redundant to publish step
# - name: build:tensorflow
#   image: plugins/docker:linux-arm
#   group: build
#   settings:
#     repo: alxda/secam
#     dry_run: true
#     dockerfile: ./rpi-tensorflow/Dockerfile
- name: publish:tensorflow
  # image: plugins/docker:linux-arm
  image: hypriot/rpi-drone
  group: docker
  settings:
    repo: alxda/secam
    dockerfile: ./rpi-tensorflow/Dockerfile
    debug: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: [ tensorflow ]

---
kind: pipeline
name: build:node-red

platform:
  os: linux
  arch: arm

clone:
  depth: 1

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
# Redundant to publish step
# - name: build:node-red
#   image: plugins/docker:linux-arm
#   group: build
#   settings:
#     repo: alxda/secam
#     dry_run: true
#     dockerfile: ./rpi-node-red/Dockerfile
- name: publish:node-red
  image: plugins/docker:linux-arm
  group: docker
  settings:
    repo: alxda/secam
    dockerfile: ./rpi-node-red/Dockerfile
    debug: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: [ node-red ]