kind: pipeline
name: build:tensorflow

platform:
  os: linux
  arch: arm

clone:
  depth: 1

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: build:tensorflow
  image: plugins/docker:linux-arm
  group: build
  settings:
    repo: alxda/secam
    dry_run: true
    dockerfile: ./rpi-tensorflow/Dockerfile
- name: publish:tensorflow
  image: plugins/docker:linux-arm
  # secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD, DOCKER_EMAIL ]
  username:
    from_secret: DOCKER_USERNAME
  password:
    from_secret: DOCKER_PASSWORD
  email:
    from_secret: DOCKER_EMAIL
  repo: alxda/secam
  tags:
    - latest
  dockerfile: ./rpi-tensorflow/Dockerfile
#   context: ./rpi-tensorflow/

---
kind: pipeline
name: build:node-red

platform:
  os: linux
  arch: arm

clone:
  depth: 1

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: build:node-red
  image: plugins/docker:linux-arm
  group: build
  settings:
    repo: alxda/secam
    dry_run: true
    dockerfile: ./rpi-node-red/Dockerfile
- name: publish:node-red
  image: plugins/docker:linux-arm
  privileged: true
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: alxda/secam
    registry: https://hub.docker.com/
    tags:
        - latest
    dockerfile: ./rpi-node-red/Dockerfile    