image: docker:latest

services:
- docker:dind

stages:
- build
# - test
# - release

variables:
  VERSION: alxda/secam:latest
  DOCKER_DRIVER: overlay2

 before_script:
   - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker info
    - docker build --pull -t $VERSION .
    - docker push $VERSION

# test:
#   stage: test
#   script:
#     - docker pull $VERSION
#     - docker run $VERSION npm test

# release:
#   stage: release
#   script:
#     - docker pull $TEST_IMAGE
#     - docker tag $TEST_IMAGE $RELEASE_IMAGE
#     - docker push $RELEASE_IMAGE
#   only:
#     - master