image: docker:stable

stages:
- build
# - test
# - release

services:
  - docker:dind

variables:
  VERSION: alxda/secam/rpi-tensorflow:latest
  DOCKER_DRIVER: overlay2

# before_script:
#    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  tags:
    - arm
  script:
    - docker info
    - docker build --build-arg BASE_IMAGE=arm32v7/debian:stretch-slim --pull -t $VERSION ./rpi-tensorflow
    - docker push $VERSION

# test:
#   stage: test
#   script:
#     - docker pull $VERSION
#     - docker run $VERSION npm test

# release:
#   stage: release
#   script:
#     - docker pull $TEST_IMAGE
#     - docker tag $TEST_IMAGE $RELEASE_IMAGE
#     - docker push $RELEASE_IMAGE
#   only:
#     - master